//priority: 50000

const FTBStructures$WorldEngine = {
  dark_void_upgrade: {
    keys: {
      a: "projecte:dark_matter_block",
      b: "xycraft_machines:void_container",
    },
    pattern: [
      ["a", " ", " ", " ", " ", " "],
      ["b", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", "m"],
    ],
  },
  infinity_upgrade: {
    keys: { a: "oritech:reactor_reflector", b: "avaritia:infinity_block" },
    pattern: [
      ["a", " ", " ", " ", " ", " "],
      ["a", " ", " ", " ", " ", " "],
      ["b", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", "m"],
    ],
  },
  euphonium_upgrade: {
    keys: { a: "ftb:euphonium" },
    pattern: [
      ["  aaa  ", " a   a ", "a     a", "a     a", "a     a", " a   a ", "  aaa  ", "       ", "       "],
      ["       ", "       ", "       ", "       ", "       ", "       ", "       ", "       ", "       "],
      ["       ", "       ", "       ", "       ", "       ", "       ", "       ", "       ", "       "],
      ["       ", "       ", "       ", "       ", "       ", "       ", "       ", "       ", "       "],
      ["       ", "       ", "       ", "       ", "       ", "       ", "       ", "       ", "       "],
      ["       ", "       ", "       ", "       ", "       ", "       ", "       ", "       ", "       "],
      ["       ", "       ", "       ", "       ", "       ", "       ", "       ", "       ", "       "],
      ["       ", "       ", "       ", "       ", "       ", "       ", "       ", "       ", "       "],
      ["       ", "       ", "       ", "       ", "       ", "       ", "       ", "       ", "   m   "],
    ],
  },
  tesseract_upgrade: {
    keys: { a: "tesseract:tesseract" },
    pattern: [
      ["a", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "m"],
    ],
  },
  chroniton_upgrade: {
    keys: { a: "ftb:chroniton_glass" },
    pattern: [
      [
        "   a a   ",
        "         ",
        "         ",
        "a       a",
        "         ",
        "a       a",
        "         ",
        "         ",
        "   a a   ",
        "         ",
      ],
      [
        "   a a   ",
        " aa   aa ",
        " a     a ",
        "a       a",
        "         ",
        "a       a",
        " a     a ",
        " aa   aa ",
        "   a a   ",
        "         ",
      ],
      [
        "   a a   ",
        "         ",
        "         ",
        "a       a",
        "         ",
        "a       a",
        "         ",
        "         ",
        "   a a   ",
        "         ",
      ],
      [
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
      ],
      [
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
      ],
      [
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
      ],
      [
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "    m    ",
      ],
    ],
  },
  quantum_tunnel_upgrade: {
    keys: { a: "ae2:quantum_ring", b: "ae2:quantum_link" },
    pattern: [
      ["   ", "aaa"],
      ["   ", "aba"],
      ["   ", "aaa"],
      ["   ", "   "],
      ["   ", "   "],
      ["   ", "   "],
      [" m ", "   "],
    ],
  },
  enchanting_upgrade: {
    keys: {
      a: "apothic_enchanting:deepshelf",
      b: "apothic_enchanting:echoing_deepshelf",
    },
    pattern: [
      ["aba", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   "],
      ["aba", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   "],
      ["   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   "],
      ["   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   "],
      ["   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   "],
      ["   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   "],
      ["   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", "   ", " m "],
    ],
  },
  ender_power_upgrade: {
    keys: { a: "powah:ender_cell_nitro" },
    pattern: [
      ["a", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " "],
      [" ", " ", " ", " ", " ", " ", " ", " ", " ", " ", "m"],
    ],
  },
  resonant_void_upgrade: {
    keys: { a: "ftb:resonant_void" },
    pattern: [
      ["a a", "   "],
      ["   ", " m "],
    ],
  },
  fortron_upgrade: {
    keys: { a: "ftb:fortron_infused_block" },
    pattern: [
      ["a   a", "     ", "     "],
      ["a   a", "     ", "     "],
      ["     ", "     ", "  m  "],
    ],
  },
  advanced_machine_upgrade: {
    keys: { a: "ftb:world_engine_advanced_machine_block" },
    pattern: [
      [
        "   a   a   ",
        "  a     a  ",
        " a       a ",
        "a         a",
        "           ",
        "           ",
        "           ",
        "a         a",
        " a       a ",
        "  a     a  ",
        "   a   a   ",
      ],
      [
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
      ],
      [
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
      ],
      [
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
      ],
      [
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
      ],
      [
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "           ",
        "     m     ",
      ],
    ],
  },
  enderium_upgrade: {
    keys: { a: "ftb:enderium_block" },
    pattern: [
      ["  a a  ", "       ", "a     a", "       ", "a     a", "       ", "  a a  ", "       ", "       "],
      ["  a a  ", "       ", "a     a", "       ", "a     a", "       ", "  a a  ", "       ", "       "],
      ["       ", "       ", "       ", "       ", "       ", "       ", "       ", "       ", "   m   "],
    ],
  },
  spirit_upgrade: {
    keys: { a: "ftb:spirit_block" },
    pattern: [
      ["a     a", "       ", "       ", "       ", "       ", "       ", "a     a", "       ", "       "],
      ["a     a", "       ", "       ", "       ", "       ", "       ", "a     a", "       ", "       "],
      ["a     a", "       ", "       ", "       ", "       ", "       ", "a     a", "       ", "   m   "],
    ],
  },
  machine_block_upgrade: {
    keys: { a: "ftb:world_engine_machine_block" },
    pattern: [
      [
        "   aaa   ",
        " aa   aa ",
        " a     a ",
        "a       a",
        "a       a",
        "a       a",
        " a     a ",
        " aa   aa ",
        "   aaa   ",
        "         ",
      ],
      [
        "    a    ",
        "         ",
        "         ",
        "         ",
        "a       a",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
      ],
      [
        "    a    ",
        "         ",
        "         ",
        "         ",
        "a       a",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
      ],
      [
        "    a    ",
        "         ",
        "         ",
        "         ",
        "a       a",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
      ],
      [
        "   aaa   ",
        " aaa aaa ",
        " a     a ",
        "aa     aa",
        "a       a",
        "aa     aa",
        " a     a ",
        " aaa aaa ",
        "   a a   ",
        "         ",
      ],
      [
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
      ],
      [
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
      ],
      [
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "    m    ",
      ],
    ],
  },
  twilight_upgrade: {
    keys: {
      a: "twilightforest:snow_queen_wall_trophy",
      b: "twilightforest:lich_trophy",
      c: "twilightforest:hydra_trophy",
      d: "twilightforest:alpha_yeti_trophy",
      e: "twilightforest:knight_phantom_trophy",
    },
    pattern: [
      [
        "    a    ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
      ],
      [
        "         ",
        "         ",
        "b       c",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "d       e",
        "         ",
      ],
      [
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "         ",
        "    m    ",
      ],
    ],
  },
  source_upgrade: {
    keys: { a: "ars_nouveau:sourcestone" },
    pattern: [
      ["a a", "   "],
      ["   ", "   "],
      ["   ", " m "],
    ],
  },
  shadow_casing_upgrade: {
    keys: {
      a: "create:shadow_steel_casing",
      b: "create:encased_chain_drive",
    },
    pattern: [
      [" aaa ", "aaaaa", "aa aa", "aaaaa", " aaa ", "     ", "     ", "     "],
      ["     ", "     ", "     ", "     ", "     ", "     ", "     ", "     "],
      ["     ", "     ", "     ", "     ", "     ", "     ", "     ", "     "],
      ["     ", "     ", "     ", "     ", "     ", "     ", "     ", "     "],
      ["     ", "     ", "     ", "     ", "     ", "     ", "     ", "     "],
      ["     ", "     ", "     ", "     ", "     ", "     ", "     ", "     "],
      ["     ", "     ", "     ", "     ", "     ", "     ", "     ", "     "],
      ["     ", "     ", "     ", "     ", "     ", "     ", "     ", "  b  "],
      ["     ", "     ", "     ", "     ", "     ", "     ", "     ", "  m  "],
    ],
  },
  draconic_upgrade: {
    keys: {
      a: "avaritia:crystal_matrix_block",
      b: "draconicevolution:energy_core_stabilizer",
      c: "draconicevolution:energy_core",
    },
    pattern: [
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "        a   a        ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "        a   a        ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "          m          ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
      ],
      [
        "          b          ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "b         c         b",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "                     ",
        "          b          ",
      ],
    ],
  },
  awakened_core_upgrade: {
    keys: {
      a: "draconicevolution:structure_block",
      b: "draconicevolution:structure_block",
    },
    pattern: [
      [
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "      m      ",
        "             ",
      ],
      [
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
      ],
      [
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
        "             ",
      ],
      [
        "             ",
        "             ",
        "             ",
        "             ",
        "    aaaaa    ",
        "    aaaaa    ",
        "    aaaaa    ",
        "    aaaaa    ",
        "    aaaaa    ",
        "             ",
        "             ",
        "             ",
        "             ",
      ],
      [
        "             ",
        "             ",
        "             ",
        "   aaaaaaa   ",
        "   abbbbba   ",
        "   abbbbba   ",
        "   abbbbba   ",
        "   abbbbba   ",
        "   abbbbba   ",
        "   aaaaaaa   ",
        "             ",
        "             ",
        "             ",
      ],
      [
        "             ",
        "             ",
        "   aaaaaaa   ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "   aaaaaaa   ",
        "             ",
        "             ",
      ],
      [
        "             ",
        "   aaaaaaa   ",
        "  abbbbbbba  ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        "  abbbbbbba  ",
        "   aaaaaaa   ",
        "             ",
      ],
      [
        "    aaaaa    ",
        "   abbbbba   ",
        "  abbbbbbba  ",
        " abbbbbbbbba ",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        " abbbbbbbbba ",
        "  abbbbbbba  ",
        "   abbbbba   ",
        "    aaaaa    ",
      ],
      [
        "    aaaaa    ",
        "   abbbbba   ",
        "  abbbbbbba  ",
        " abbbbbbbbba ",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        " abbbbbbbbba ",
        "  abbbbbbba  ",
        "   abbbbba   ",
        "    aaaaa    ",
      ],
      [
        "    aaaaa    ",
        "   abbbbba   ",
        "  abbbbbbba  ",
        " abbbbbbbbba ",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbb bbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        " abbbbbbbbba ",
        "  abbbbbbba  ",
        "   abbbbba   ",
        "    aaaaa    ",
      ],
      [
        "    aaaaa    ",
        "   abbbbba   ",
        "  abbbbbbba  ",
        " abbbbbbbbba ",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        " abbbbbbbbba ",
        "  abbbbbbba  ",
        "   abbbbba   ",
        "    aaaaa    ",
      ],
      [
        "    aaaaa    ",
        "   abbbbba   ",
        "  abbbbbbba  ",
        " abbbbbbbbba ",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        "abbbbbbbbbbba",
        " abbbbbbbbba ",
        "  abbbbbbba  ",
        "   abbbbba   ",
        "    aaaaa    ",
      ],
      [
        "             ",
        "   aaaaaaa   ",
        "  abbbbbbba  ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        " abbbbbbbbba ",
        "  abbbbbbba  ",
        "   aaaaaaa   ",
        "             ",
      ],
      [
        "             ",
        "             ",
        "   aaaaaaa   ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "  abbbbbbba  ",
        "   aaaaaaa   ",
        "             ",
        "             ",
      ],
      [
        "             ",
        "             ",
        "             ",
        "   aaaaaaa   ",
        "   abbbbba   ",
        "   abbbbba   ",
        "   abbbbba   ",
        "   abbbbba   ",
        "   abbbbba   ",
        "   aaaaaaa   ",
        "             ",
        "             ",
        "             ",
      ],
      [
        "             ",
        "             ",
        "             ",
        "             ",
        "    aaaaa    ",
        "    aaaaa    ",
        "    aaaaa    ",
        "    aaaaa    ",
        "    aaaaa    ",
        "             ",
        "             ",
        "             ",
        "             ",
      ],
    ],
  },
};

const FTBStructures$AdvancedEmpowerer = {
  main: {
    pattern: [
      ["abbba", "bbbbb", "bbbbb", "bb bb", "abmba"],
      [" bcb ", "b d b", "cdedc", "b d b", " bcb "],
      ["  a  ", " aca ", "acfca", " aca ", "  a  "],
    ],
    keys: {
      a: "immersiveengineering:slab_sheetmetal_colored_purple",
      b: "immersiveengineering:sheetmetal_colored_purple",
      c: "minecraft:tinted_glass",
      d: "actuallyadditions:display_stand",
      e: "actuallyadditions:empowerer",
      f: "actuallyadditions:ender_casing",
    },
  },
};

const FTBStructures$CircuitFabricator = {
  main: {
    pattern: [
      ["aaa", "a a", "ama"],
      ["aba", "bcb", "a a"],
      ["aaa", "aaa", "a a"],
    ],
    keys: {
      a: "immersiveengineering:sheetmetal_colored_blue",
      b: "ae2:quartz_vibrant_glass",
      c: "ae2:mysterious_cube",
    },
  },
};

const FTBStructures$NeutronActivator = {
  main: {
    pattern: [
      ["aaa", "a a", "aaa", " m "],
      ["aba", "bcb", "aba", "   "],
      ["aba", "bdb", "aba", "   "],
      ["aaa", "aea", "aaa", "   "],
    ],
    keys: {
      a: "oritech:carbon_plating_block",
      b: "cognition:whisperglass",
      c: "oritech:reactor_reflector",
      d: "oritech:reactor_vent",
      e: "actuallyadditions:empowered_void_crystal_block",
    },
  },
};

const FTBStructures$ALL = {
  "ftb:world_engine": FTBStructures$WorldEngine,
  "ftb:advanced_empowerer": FTBStructures$AdvancedEmpowerer,
  "ftb:circuit_fabricator": FTBStructures$CircuitFabricator,
  "ftb:neutron_activator": FTBStructures$NeutronActivator,
};
